version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my_network
    # Other configurations for your frontend service

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_network
    # Other configurations for your backend service

networks:
  my_network:
    driver: bridge

# Additional services or configurations can be added here if needed
