version: '3'

services:
  frontend:
    image: deepakprasad/frontend:9
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - my_network
    # Other configurations for your frontend service

  backend:
  
    image: deepakprasad/backend:9
    ports:
      - "5000:5000"
    networks:
      - my_network
    # Other configurations for your backend service

networks:
  my_network:
    driver: bridge

# Additional services or configurations can be added here if needed
