name: Build and Update Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_update_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build frontend Docker image
        run: |
          FRONTEND_TAG=${{ github.run_number }}
          docker build -t frontend:$FRONTEND_TAG ./frontend
          echo "::set-output name=frontend_tag::$FRONTEND_TAG"

      - name: Build backend Docker image
        run: |
          BACKEND_TAG=${{ github.run_number }}
          docker build -t backend:$BACKEND_TAG ./backend
          echo "::set-output name=backend_tag::$BACKEND_TAG"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push frontend Docker image to Docker Hub
        run: |
          FRONTEND_TAG=${{ steps.build_and_update_images.outputs.frontend_tag }}
          docker tag frontend:$FRONTEND_TAG ${{ secrets.DOCKERHUB_USERNAME }}/frontend:$FRONTEND_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:$FRONTEND_TAG

      - name: Push backend Docker image to Docker Hub
        run: |
          BACKEND_TAG=${{ steps.build_and_update_images.outputs.backend_tag }}
          docker tag backend:$BACKEND_TAG ${{ secrets.DOCKERHUB_USERNAME }}/backend:$BACKEND_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:$BACKEND_TAG

